rabbitstack/fibratus

fibratus/controller.py

A space to the right of a backslash would break your script yet it is invisible to the reader.
|= shortens long lines and executes faster.
Or will gracefully deal with other Falsey values such as: [], {}, 0, False, etc.

Avoid backslash line continuation, |=, simplify with or

---

README.md

Now backers and sponsors on open collective will appear directly on your readme. [Here](https://github.com/webpack/webpack#backers) is an example of how it'll look.
Also add badges on top. 
[User guide](https://github.com/OpenCollective/OpenCollective/wiki/Github-banner) for more info.

add backers&sponsors to your readme

---

pkg/filter/accessor.go
pkg/filter/fields/fields.go
pkg/filter/fields/fields_test.go
pkg/filter/filter_test.go
pkg/handle/types/types.go
pkg/kevent/formatter.go
pkg/kevent/marshaller.go
pkg/kevent/marshaller_test.go
pkg/ps/snapshotter.go
pkg/ps/snapshotter_test.go
pkg/ps/types/types.go
pkg/ps/types/types_test.go

Filter fields for creating expressions that evaluate parent process attributes such as parent process name, sid, command line, and so on. Besides this, it is also possible to obtain the `nth` parent process in the process ancestry by using the field path syntax.
Example:
```
ps.parent[2].name = 'powershell.exe'
```
This filter would match all events where the process grandparent name is `powershell.exe`.

feat(filter): Parent process filters

---

pkg/filter/accessor.go
pkg/filter/fields/fields.go
pkg/filter/fields/fields_test.go
pkg/filter/filter_test.go
pkg/filter/ql/ast.go
pkg/ps/types/types.go
pkg/ps/types/types_test.go

In light of #71, this PR further expands the ancestry traversing. It is possible to use the `ps.parent[any].*` field path to return process values of all ancestor processes.
Example:
```
$ fibratus run ps.parent[any].name in ('powershell.exe', 'winword.exe')
```
Would match all events where any of its ancestors is `powershell.exe` or `winword.exe` process.

feat(filter): Any parent filters for ancestry traversing

---

pkg/filter/rules.go
pkg/filter/rules_test.go
pkg/kevent/formatter_test.go
pkg/kevent/kevent.go

When a rule is triggered, the rule and group name to which it pertains are pushed into event's metadata.

feat(rules): add include group rules in event metadata

---

docs/_coverpage.md
docs/yara/alerts.md
pkg/filter/rules.go
pkg/kstream/interceptors/image_windows.go
pkg/kstream/interceptors/ps_windows.go
pkg/yara/scanner.go
pkg/yara/scanner_test.go
pkg/yara/types.go

To streamline the association of events with the respective YARA rule matches, a new tag, `yara.matches` is injected into event metadata. It contains the JSON representation of all the rule matches. Example:
```json
[
{
"Rule": "AnglerEKredirector ",
"Namespace": "EK",
"Tags": null,
"Metas": [
{
"Identifier": "description",
"Value": "Angler Exploit Kit Redirector"
}
],
"Strings": "..."
},
{
"Rule": "angler_flash_uncompressed ",
"Namespace": "EK",
"Tags": [
"exploitkit"
],
"Metas": [
{
"Identifier": "description",
"Value": "Angler Exploit Kit Detection"
}
],
"Strings": "..."
}
]
```

feat(yara): Rule matches as tags in event metadata

---

pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
pkg/fs/attrs.go
pkg/kevent/kparam_windows.go
pkg/kevent/kparams/canonicalize.go
pkg/kevent/kparams/size.go
pkg/kevent/marshaller_windows.go
pkg/kstream/interceptors/fs_windows.go

This PR adds support for a new `attributes` parameter in `CreateFile` events that represent all of the requested file attributes. An example of the `CreateFile` event with temporary and hidden attributes:
```
21156 2022-06-24 11:49:54.1806558 +0200 CEST - 2 firefox.exe (6404) - CreateFile (attributes➜ [hidden temporary], file_name➜ C:\Users\emoji\AppData\Roaming\Microsoft\Windows\Recent\CustomDestinations\6824f4a902c78fbd.customDestinations-ms~RF3c9f39.TMP, file_object➜ ffff9c8bd292a730, irp➜ ffff9c8bcd2eca88, operation➜ create, share_mask➜ ---, type➜ file)
```

feat(events): file attributes parameter in CreateFile events

---

pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
pkg/kstream/interceptors/fs_windows.go
pkg/kstream/interceptors/ps_windows.go
pkg/kstream/interceptors/registry_windows.go
pkg/kstream/interceptors/util.go

With this PR we have the ability to observe and filter `CreateFile` events by the status message that includes the outcome of the operation. Closes #106 
An example of  the `CreateFile` event with the `status` parameter:
```
53861 2022-06-25 20:00:30.310177 +0200 CEST - 1 aswidsagent.exe (7880) - CreateFile (file_name➜ C:\PROGRAM FILES (X86)\COMMON FILES\ORACLE\JAVA\JAVAPATH\DEVICE\NULL, file_object➜ ffff8002915865d0, irp➜ ffff80028a4c6598, operation➜ supersede, share_mask➜ rw-, status➜ a reparse should be performed by the object manager since the name of the file resulted in a symbolic link., type➜ directory)
```

feat (events): add the `status` parameter to CreateFile events

---

pkg/config/schema_windows.go

This PR allows specifying `OpenProcess` and `OpenThread` events in rule group selectors. Closes #120

fix: include `OpenThread` and `OpenProcess` selectors

---

configs/rules/default/default.yml
configs/rules/default/stateful.yml
go.mod
go.sum
pkg/config/_fixtures/filters/default-new-attributes.yml
pkg/config/filters.go
pkg/config/filters_test.go
pkg/config/schema_windows.go
pkg/errors/errors.go
pkg/filter/_fixtures/sequence_policy_complex_pattern_bindings.yml
pkg/filter/_fixtures/sequence_policy_simple.yml
pkg/filter/_fixtures/sequence_policy_simple_max_span.yml
pkg/filter/_fixtures/sequence_policy_simple_pattern_bindings.yml
pkg/filter/filter.go
pkg/filter/filter_test.go
pkg/filter/filter_windows.go
pkg/filter/funcmap/funcmap_windows.go
pkg/filter/ql/ast.go
pkg/filter/ql/lexer.go
pkg/filter/ql/lexer_test.go
pkg/filter/ql/literal.go
pkg/filter/ql/parser.go
pkg/filter/ql/parser_test.go
pkg/filter/ql/token.go
pkg/filter/rules.go
pkg/filter/rules_test.go
pkg/kevent/kparam.go
pkg/kstream/kstreamc_windows.go
pkg/util/atomic/atomic.go

This is a non-trivial PR that brings the concept of stateful detection rules. It is based on the idea of sequence rule groups. Traditionally in Fibratus, one could use either exclude or include event policies with their corresponding relations. The sequence rule group policy allows the implementation of rules that are triggered as the ordered sequence of events is being matched against the rules. Additionally, the rules can define pattern bindings to link the same set of events that matched in one rule to the subsequent rules. It is also possible to specify the max time span between the matching phase of multiple rules. To demonstrate the idea of sequence rules, let's see a naive example that detects the execution of the browser client followed by the creation of the PDF file by the same …

feat (rules): Stateful detection rules

---

pkg/kevent/kparam.go
pkg/kevent/kparam_test.go
pkg/kstream/interceptors/ps_windows.go
pkg/kstream/interceptors/ps_windows_test.go
pkg/ps/types/types_windows.go
pkg/ps/types/types_windows_test.go

This PR fixes the normalization of the process cmdline. Previously, the command line wasn't mutated after applying the normalization. The command line `SystemRoot` env var is expanded prior to determining the executable full path.

fix: Process command line normalization

---

pkg/filament/cpython/dict_test.go
pkg/filament/cpython/gil_test.go
pkg/filament/cpython/interpreter_test.go
pkg/filament/cpython/module_test.go
pkg/filament/filament_test.go
pkg/filter/filter_test.go
pkg/filter/filter_windows.go
pkg/filter/ql/error.go
pkg/filter/ql/error_test.go
pkg/filter/ql/lexer.go
pkg/filter/ql/parser.go
pkg/filter/rules.go

In the case of multiline rules, if there is a syntax error in the filter the error reporting couldn't indicate the exact position in the expression where the malformed element is present. This PR improves the error reporting. Example:
```
Error: invalid filter "Core Windows keys" in "Suspicious registry key modifications" group: kevt.name in ('RegCreateKey', 'RegDeleteKey', 'RegSetValue', 'RegDeleteValue')
and
registry.key.name icontains
(
'CurrentVersion\\Run',
'Windows\\System\\Scripts',
'CurrentVersion\\Windows\\Load',
'CurrentVersion\\Windows\\Run',
'CurrentVersion\\Winlogon\\Shell',
'CurrentVersion\\Winlogon\\System',
'UserInitMprLogonScript'
)
or
registry.key.name istartswith
(
'HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\Notify', …
```

feat(filter): Beautify filter error reporting

---

configs/fibratus.yml
pkg/config/config_windows.go
pkg/config/kstream.go
pkg/config/schema_windows.go
pkg/handle/types.go
pkg/kevent/kparam.go
pkg/kevent/kparams/canonicalize.go
pkg/kevent/ktypes/category.go
pkg/kevent/ktypes/ktypes_windows.go
pkg/kevent/ktypes/metainfo_windows.go
pkg/kstream/controller_windows.go
pkg/kstream/controller_windows_test.go
pkg/kstream/interceptors/chain_windows.go
pkg/kstream/interceptors/driver.go
pkg/kstream/interceptors/handle_windows.go
pkg/kstream/interceptors/handle_windows_test.go
pkg/kstream/interceptors/interceptor.go
pkg/kstream/kstreamc_windows.go
pkg/syscall/driver/driver.go
pkg/syscall/driver/driver_test.go
pkg/syscall/etw/types.go

This PR introduces the `Microsoft-Antimalware-Engine` ETW provider as another source of events. In particular, this provider emits events related to the loading of kernel drivers, even though it doesn't provide any parameters to designate the signature state of the driver being loaded. Because this provider requires Microsoft Defender Antivirus real-time protection to be enabled, an alternative method for detecting driver loading/unloading has been introduced and relies on tracking the object manager events targeting the `Driver` object types.

feat: Driver loading events

---

pkg/kevent/kparams/readers.go
pkg/syscall/utf16/string.go
pkg/syscall/utf16/string_test.go

This PR delivers a custom UTF-16 decoding function that significantly outperforms the stdlib equivalent. Benchmarks results:
```
BenchmarkStdlibDecode
BenchmarkStdlibDecode-8   	69832465	        15.93 ns/op	       5 B/op	       0 allocs/op
BenchmarkDecode
BenchmarkDecode-8   	311599040	         3.873 ns/op	       3 B/op	       0 allocs/op
```

perf: Speed up UTF-16 decoding

---

pkg/filter/_fixtures/default/default.yml
pkg/filter/_fixtures/sequence_and_simple_rule_mix.yml
pkg/filter/_fixtures/sequence_rule_bound_fields.yml
pkg/filter/_fixtures/sequence_rule_simple.yml
pkg/filter/_fixtures/sequence_rule_simple_max_span.yml
pkg/filter/filter.go
pkg/filter/filter_test.go
pkg/filter/ql/ast.go
pkg/filter/ql/error_test.go
pkg/filter/ql/function_test.go
pkg/filter/ql/lexer.go
pkg/filter/ql/literal.go
pkg/filter/ql/parser.go
pkg/filter/ql/parser_test.go
pkg/filter/ql/token.go
pkg/filter/rules.go
pkg/filter/rules_test.go

Bound fields is the new functionality of the rule engine that permits linking sequence events by sharing the properties of the aliased event. The following example illustrates the use of bound fields:
```
sequence
maxspan 200ms
|kevt.name = 'CreateProcess' and ps.name = 'cmd.exe'| as e
|kevt.name = 'CreateFile'
and
file.name icontains 'temp'
and
$e.ps.sid = ps.sid
| 
````
We first declare the event alias using the `AS` keyword and reference the bound fields by prefixing the `$` symbol before the alias name.

feat(rules): Bound fields

---

pkg/filter/ql/function.go
pkg/filter/ql/functions/get_reg_value.go
pkg/filter/ql/functions/get_reg_value_test.go
pkg/filter/ql/functions/types.go

The `GET_REG_VALUE` filter function permits retrieving the content of the given registry value. The value is supplied in FQKN form. For example, to get the content of the `HKEY_CURRENT_USER\Control Panel\Personalization\Desktop Slideshow\Shuffle` value, we could have the following expression:
```
get_reg_value('HCU\Control Panel\Personalization\Desktop Slideshow\Shuffle') = 0
```

feat(filter): Function for getting registry values

---

pkg/filter/accessor.go
pkg/filter/accessor_windows.go
pkg/filter/filter.go
pkg/filter/filter_test.go
pkg/filter/filter_windows.go

If downstream sequence expressions are referencing unknown or invalid bound fields, the filter engine should throw an error highlighting the invalid bound field reference.

chore(filter): Ensure correctness of bound field references

---

pkg/filter/accessor.go
pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
pkg/filter/fields/fields_windows_test.go
pkg/filter/filter_test.go

`kevt.arg` represents a generic filter field capable of extracting any parameter from the incoming event. The parameter name matches the internal key used to index the parameter. For example, `kevt.arg[exe]` would extract the `exe` parameter from the event parameters.

feat(filter): Generic event argument filter field

---

pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
pkg/kevent/kparam_windows.go
pkg/kevent/kparams/fields_windows.go
pkg/kstream/kstreamc_windows_test.go
pkg/kstream/processors/image_windows.go
pkg/kstream/processors/image_windows_test.go
pkg/pe/parser.go
pkg/pe/types.go
pkg/sys/syscall.go
pkg/sys/trust.go
pkg/sys/zsyscall_windows.go
pkg/util/format/format.go
pkg/util/signature/cat.go
pkg/util/signature/cat_test.go
pkg/util/signature/signature.go
pkg/util/signature/signature_test.go
pkg/util/signature/types.go
rules/macros/macros.yml

This PR delivers new `ImageLoad` event parameters to designate the type and level of the image/module signature. Since the event parameters published by ETW are frequently reported with unchecked signature type even for core Windows binaries and DLLs, it is necessary to manually check whether the module is signed and also if it is a trusted image - i.e. the trust chain is verified following certificates to a trusted root certificate.
Various rule macros are delivered as part of this PR and ready to use in detection rules (should be self-explanatory):
- `load_unsigned_module`
- `load_untrusted_module`
- `load_unsigned_or_untrusted_module`

feat(kevent): Introduce image signature event parameters and rule macros

---

pkg/handle/object.go
pkg/kevent/backlog.go
pkg/kevent/kevent_windows.go
pkg/kevent/kparam_windows.go
pkg/kevent/kparams/fields_windows.go
pkg/kevent/ktypes/ktypes_windows.go
pkg/kevent/ktypes/metainfo_windows.go
pkg/kstream/kstreamc_windows_test.go
pkg/kstream/processors/chain_windows.go
pkg/kstream/processors/handle_windows.go
pkg/kstream/processors/handle_windows_test.go
pkg/outputs/eventlog/eventlog.go
pkg/outputs/eventlog/mc/fibratus.mc
rules/macros/macros.yml

Introduce support for the `DuplicateHandle` event. As its name suggests, this event is captured as a response to the handle duplication operations.

feat(kevent): New DuplicateHandle event

---

pkg/filter/rules.go

We used to dump the entire rule structure, instead of just accessing the rule name, so this PR fixes the problem.

fix(filter): Use just rule name in filter field deprecation log message

---

pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
pkg/kevent/backlog.go
pkg/kevent/kevent.go
pkg/kevent/kevent_windows.go
pkg/kevent/kparams/fields_windows.go
pkg/kstream/processors/fs_windows.go
pkg/kstream/processors/handle_windows.go
pkg/kstream/processors/image_windows.go
pkg/kstream/processors/image_windows_test.go
pkg/pe/parser.go
pkg/pe/types.go
pkg/ps/snapshotter_windows.go
pkg/ps/snapshotter_windows_test.go
pkg/ps/types/types_windows.go
pkg/util/signature/cat.go
pkg/util/signature/cat_test.go
pkg/util/signature/signature.go
pkg/util/signature/signature_test.go
pkg/util/signature/types.go

In addition to signature type and signature level parameters, it is valuable to gain access to the certificate parameters. This PR decorated image load events with signature certificate params and exposes a set of filter fields to access the certificate info.

feat: Certifcate params/filter fields in PE images

---

pkg/kstream/processors/image_windows.go
pkg/util/signature/signature.go
pkg/util/signature/signature_test.go
pkg/util/signature/types.go

This PR improves the signature checking/verification logic by moving the certificate parsing into a separate function. Also, a new enumeration value for file-verified signature types is added.

refactor: Untangle signature checking/verification from certifcate fetching

---

pkg/kstream/processors/image_windows_test.go
pkg/util/signature/signature.go

Due to leftovers from previous logic, the `signtature.Check` function had a misleading comment, so this PR takes care of fixing the function comment, in addition to expanding the image signature tests.

refactor: Fix function misleading comment and improve tests

---

pkg/filter/ql/functions/yara.go
pkg/filter/ql/functions/yara_test.go
pkg/yara/scanner.go
pkg/yara/scanner_test.go

One possible cause of Yara scanner stalls could be the explicit disposal of the scanner instance. Thus, let's try to delegate the scanner destruction to the runtime finalizer and check if the issue persists.

fix: Diagnose Yara scanner hanging indefinitely 

---

pkg/filter/accessor_windows.go
pkg/pe/parser.go

Initialize PE data as part of the `goto` jump and remove unused PE functions that were leftovers of the previous resource parsing functionality.

fix: Make sure PE is initialized during the goto jump

---

rules/macros/macros.yml
rules/persistence_boot_or_logon_autostart_execution.yml

For the sake of keeping the rules files as readable as possible, we're moving the persistence registry keys and startup shell folder keys into respective macro lists.

refactor(rules): Move registry keys into macro lists

---

internal/bootstrap/bootstrap.go
internal/bootstrap/config.go

To eliminate the dependency on the configuration file, this change permits starting Fibratus without a config file. In this case, sane default config values will be used and the log message is emitted to inform about this situation.

chore: Lift config file obligation

---

pkg/config/config_windows.go
pkg/util/log/config.go
pkg/util/log/logger.go

Rules and macros are loaded from the installation path by default. This will ease the onboarding of future users.

chore: Initialize default rules paths and override logger settings

---

rules/macros/macros.yml

The conditions are refined to improve the efficiency of rule matching by discarding unspecified, loopback addresses, and RFC1918 address spaces.

chore(rules): Improve inbound/outbound network macros

---

pkg/kevent/kparam.go

Various flag/enum parameter specifiers were overlooked, so this PR takes care of addressing the defect.

fix(kcap): Add missing flag/enum parameter values in kcap param constructor

---

.github/workflows/master.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.golangci.yml
go.mod
pkg/util/fasttemplate/unsafe.go
pkg/util/typesize/typesize.go

The Go version is indicated by the global env variable, in addition to bumping the deprecated actions. This also required upgrading the golangci-lint tool as it is apparently not compatible with the newer Go version.

chore(ci): Upgrade Go and update deprecated actions

---

pkg/kevent/kevent_windows.go
pkg/kstream/processors/image_windows.go
pkg/kstream/processors/ps_windows.go
pkg/ps/snapshotter_windows.go
pkg/ps/snapshotter_windows_test.go
pkg/ps/types/types_windows.go
pkg/util/cmdline/cmdline.go
pkg/util/cmdline/cmdline_test.go

If the executable image in the command line is reported without extension, the `exe` parameter is augmented from the image name parameter. Whenever the executable path lacks the FQFN, we resolve the full executable path from the image events and
mutate the process state accordingly. 
Remove spurious attribution of pid zero to be equal to the pid of the process generating the event. This should be the `System` process pid instead.
Process image rundown events in the processor. This condition was overlooked from the previous refactoring.

fix: Harden command line parsing and exe enrichment

---

configs/fibratus.yml
pkg/config/config_windows.go
pkg/config/schema_windows.go
pkg/handle/snapshotter.go
pkg/handle/snapshotter_test.go
pkg/kstream/consumer_windows_test.go

Collecting process handles has a significant impact on memory utilization. This is why we offer the config flag `handle.enumerate-handles` for controlling handle enumeration. It is off by default.

feat(handle): Control process handle enumeration

---

internal/bootstrap/bootstrap.go
pkg/errors/errors_windows.go
pkg/kcap/writer_windows_test.go
pkg/kevent/sequencer_windows.go
pkg/kstream/consumer_windows.go
pkg/kstream/consumer_windows_test.go
pkg/kstream/controller_windows.go
pkg/kstream/controller_windows_test.go
pkg/sys/etw/etw.go
pkg/sys/etw/types.go

The motivation for restructuring the trace management is driven by two major areas:
1. reducing code duplication in trace controller
2. making adding future ETW providers less painful as the consumer is aware of which traces are registered and started

refactor: Revamp trace controller and consumer

---

rules/credential_access_modify_authentication_process.yml
rules/credential_access_os_credential_dumping.yml
rules/initial_access_phishing.yml
rules/macros/macros.yml

Several changes are introduced to address the following points:
- reduce false positives in `SAM dump through registry rule` by converting into sequence
- use `CreateFile` event type in `write_minidump_file` macro
- use `outbound_network` macro in `Potential credentials dumping or exfiltration via malicious password filter DLL` to reduce alert fatigue
- `LSASS memory dumping via legitimate or offensive tools` rule checks for `VM_READ` access right
- initial access rules are both using `create_file` macros instead of `write_file` and have an additional check for image characteristics
- unused macros are removed

chore(rules): Improve rules

---

.github/workflows/rules.yml

Fibratus binary needs to be downloaded from the artifacts tied to the specific workflow.

fix(ci): Download artifact from workflow

---

.github/workflows/pr.yml
.github/workflows/rules.yml

`msiexec `launches the installation of Fibratus in the background and returns immediately. The side effect is that the next step will never find the Fibratus binary ready to run the rules validation. The solution consists of waiting for the `msiexec `process to complete before executing the next step

fix(ci): Wait for MSI install

---

pkg/config/kstream.go
pkg/config/kstream_test.go
pkg/config/schema_windows.go
pkg/kevent/kevent_windows.go
pkg/kevent/ktypes/metainfo_windows.go
pkg/kstream/consumer_windows.go

To avoid processing uninterested events at later stages of the event consumer, such as event parsing or processor traversing, drop events coming from the current process as soon as possible. Additionally, excluded event types are dropped after the event type descriptor is constructed.

perf: More efficient event dropping

---

pkg/config/_fixtures/filters/default.yml
pkg/config/filters.go
pkg/config/schema_windows.go
pkg/filter/_fixtures/kill_action.yml
pkg/filter/rules.go
rules/credential_access_credentials_from_password_stores.yml
rules/credential_access_modify_authentication_process.yml
rules/persistence_boot_or_logon_autostart_execution.yml

Individual rule validation would only apply to the first rule in the array. After adding pertinent adjustments to the JSON schema, all rules are validated through the schema. As a consequence of these changes, the filter actions structure is reorganized to satisfy schema requirements.

fix(rules): Fix rules schema validation

---

cmd/fibratus/app/rules/list.go
cmd/fibratus/app/rules/rules.go
cmd/fibratus/app/rules/validate.go

The new subcommand is able to list all rules contained in the local detection rules catalog. It can also receive the `-s` option to show the summary of rules per MITRE tactic/technique. Example:
```
┌────────────────────────────────────────────────────┬─────────┐
│ TACTIC                                             │ # RULES │
├────────────────────────────────────────────────────┼─────────┤
│ Persistence                                        │ 6       │
│ Credential Access                                  │ 17      │
│ Defense Evasion                                    │ 2       │
│ Initial Access                                     │ 2       │
├────────────────────────────────────────────────────┼─────────┤
│ TECHNIQUE                                          │ # RULES │ …
```

feat(cli): Implement list rules command

---

.github/workflows/rules.yml
make.bat

Instead of populating the workflow with commands needed to install the MSI, the targets are defined in the Make.bat file
to foment the reuse of the aforementioned commands.

chore(build): Create targets for MSI installation

---

.github/workflows/rules.yml
make.bat

If the rules validate target fails, also mark the workflow as failed. Export the `PATH` directly in the workflow manifest.

fix(ci): Rules workflow fixes

---

configs/fibratus.yml
internal/bootstrap/bootstrap.go
pkg/config/config_windows.go
pkg/config/filters.go
pkg/config/schema_windows.go

If the user wants to completely disable the rule engine, it can do this by setting the `filters.rules.enabled` flag to false. When the rule engine is disabled, all events matching the CLI filters are routed to output sinks.

feat(config): Permit disabling rule engine

---

rules/persistence_boot_or_logon_autostart_execution.yml
rules/persistence_office_application_startup.yml

Detects when attackers drop macro-enabled files in specific folders to trigger their execution every time the victim user opens an Office application.

feat(rule): Suspicious Office template created

---

go.mod
go.sum
pkg/config/kstream.go
pkg/config/kstream_test.go
pkg/kevent/ktypes/eventset.go
pkg/kevent/ktypes/eventset_test.go
pkg/kevent/ktypes/ktypes_windows.go
pkg/kstream/consumer_windows.go
pkg/sys/etw/types.go

When testing if a particular event type is contained in the exclude list, we keep a map of event types to boolean values. As this is not very efficient, a bitset-backed data structure is used to set and test different event types.

perf: Eventset masks

---

pkg/kcap/writer_windows.go
pkg/kevent/marshaller_windows.go
pkg/kevent/queue.go

When there are no listeners registered on the event queue, the event is not pushed to the channel, and so, neither is written to the capture.
The callstack parameters are slices of uint64 values. The marshaling logic didn't contemplate those, leading to slice out-of-bounds crashes. 
This changeset takes care of both defects.

fix(capture): Empty capture file and replay crashes

---

configs/fibratus.yml
internal/bootstrap/bootstrap.go
pkg/config/config_windows.go
pkg/config/filters.go
pkg/config/kstream.go
pkg/config/schema_windows.go
pkg/filter/_fixtures/default/default.yml
pkg/filter/rules.go
pkg/filter/rules_test.go
pkg/kcap/writer_windows_test.go
pkg/kevent/ktypes/eventset.go
pkg/kevent/ktypes/ktypes_windows.go
pkg/kstream/consumer_windows_test.go
pkg/kstream/controller_windows.go
pkg/kstream/controller_windows_test.go
rules/credential_access_os_credential_dumping.yml

To optimize resource consumption and avoid processing events that are not used in the ruleset, this new mechanism
permits to dynamically enable event categories or providers depending on what event types are present in the loaded
ruleset.

feat(rules): Dynamic event flags enablement

---

cmd/fibratus/app/stats/stats.go
pkg/config/config_windows.go
pkg/config/kstream.go
pkg/kevent/callstack_test.go
pkg/kevent/kevent_windows.go
pkg/kevent/ktypes/eventset.go
pkg/kevent/ktypes/ktypes_windows.go
pkg/kevent/queue.go
pkg/kevent/queue_test.go
pkg/kstream/consumer_windows.go
pkg/kstream/consumer_windows_test.go
pkg/kstream/controller_windows.go
pkg/kstream/controller_windows_test.go
pkg/kstream/stackext.go
pkg/kstream/stackext_test.go
pkg/pe/types.go
pkg/sys/etw/types.go
pkg/util/key/key.go

When granular system provider support is detected, the kernel trace session only emits file I/O
events. The remaining events are published by their respective system providers. This speeds up delivering events from the session buffers which is integral to achieving near real-time detections.

feat: Introduce system providers support

---

internal/bootstrap/bootstrap.go
pkg/config/config_windows.go
pkg/kevent/callstack.go
pkg/kstream/consumer_windows_test.go
pkg/ps/snapshotter.go
pkg/ps/snapshotter_mock.go
pkg/ps/snapshotter_windows.go
pkg/symbolize/symbolizer.go
pkg/symbolize/symbolizer_test.go

Stack return address symbolization is performed from process modules and symbol data obtained from the PE export directory. Debug Help API is used when either the module is not found or symbol information can't be resolved.

perf(stack-enrichment): Boost stack enrichment performance

---

rules/credential_access_os_credential_dumping.yml
rules/defense_evasion_system_binary_proxy_execution.yml

Add additional command line patterns for lolbins, point function calls, and ADS executions. Also, include a couple of exceptions in `Potential SAM database dump through registry` rule.

chore(rules): Improve `System Binary Proxy Execution via Rundll32` rule

---

pkg/config/_fixtures/filters/default.yml
pkg/config/filters.go
pkg/config/filters_test.go
pkg/config/schema_windows.go
pkg/filter/_fixtures/kill_action.yml
pkg/filter/action/kill_windows.go
pkg/filter/rules.go
pkg/util/convert/convert_test.go

Introducing a field to specify which process id is used to terminate the process may be convoluted and at the same time superfluous to handle. For this reason, the pid field is removed from the action definition, and the action automatically collects pids to be killed by walking event matches.

refactor(rule-engine): Remove kill action `pid` field

---

rules/defense_evasion_process_injection.yml

Detects when adversaries abuse the NTFS transactional API functions to overwrite the legitimate executable with shellcode and then create a section object from the malicious file. The tainted section is used to spawn a new process via the undocumented NtCreateProcessEx native API function.

feat(rule): New `Potential Process Doppelganging` rule

---

pkg/filter/action/kill_windows.go
pkg/filter/ql/literal.go
pkg/filter/ql/parser.go
pkg/filter/ql/parser_test.go
pkg/filter/rules.go
pkg/kevent/ktypes/ktypes_windows.go
pkg/kevent/ktypes/ktypes_windows_test.go

Some sequence expressions contain events that may arrive out of order. Only for such expressions the sequence evaluation should honor out-of-order partials. If the sequence references out-of-order events but all pertain to the same provider, then the sequence can be denoted as ordered.

perf(rule-engine): Determine sequence ordering

---

rules/defense_evasion_process_injection.yml
rules/macros/macros.yml

This rule identifies process hollowing injection attempts by spawning a legitimate process in a suspended state. The code section of the process' executable in-memory image is unmapped and replaced enabling the veiled execution of malicious code.

feat(rules): New `Potential Process Hollowing` rule

---

rules/credential_access_modify_authentication_process.yml

Attackers can abuse Windows Security Support Provider and Authentication Packages to dynamically inject a Security Package into the Local Security Authority Subsystem Service process to intercept all logon passwords. This rule supersedes the `Potential credentials dumping or exfiltration via malicious password filter DLL` rule.

refactor(rule): Suspicious DLL loaded by LSASS

---

pkg/kevent/kevent_windows.go
pkg/kevent/kevent_windows_test.go

The partial key wasn't computed correctly for `OpenProcess/OpenThread` events because of insufficient slice length. The partial key wasn't calculated for `MapViewFile`` event, and additionally, the hash should be computed against the view base address instead of the file key.

fix(kevent): Revisit partial key computation

---

pkg/filter/accessor.go
pkg/filter/accessor_windows.go
pkg/filter/accessor_windows_test.go
pkg/filter/fields/fields_windows.go
pkg/filter/filter.go
pkg/filter/filter_test.go
pkg/filter/filter_windows.go
pkg/kevent/callstack.go
pkg/kevent/callstack_test.go
pkg/kevent/kparam.go
pkg/kevent/queue.go
pkg/kstream/consumer_windows.go
pkg/kstream/consumer_windows_test.go
pkg/kstream/processors/fs_windows.go
pkg/kstream/processors/image_windows.go
pkg/kstream/processors/image_windows_test.go
pkg/kstream/processors/net_windows.go
pkg/kstream/processors/net_windows_test.go
pkg/network/dns.go
pkg/network/dns_test.go
pkg/symbolize/symbolizer.go
pkg/util/cmdline/cmdline.go
pkg/util/cmdline/cmdline_test.go
pkg/util/signature/signature.go
pkg/util/signature/signature_test.go
pkg/util/signature/types.go
rules/credential_access_os_credential_dumping.yml
rules/defense_evasion_process_injection.yml
rules/persistence_boot_or_logon_autostart_execution.yml

Reverse DNS enrichment and image signature checking are both moved to accessors. The accessor interface is refactored and a new `IsFieldAccessible` method will only evaluate an event against the accessor if the condition is met. As part of this refactoring, instead of trying to flush the queue on each event, a periodical timer will traverse the queue and flush any events that remained in deque more time than allowed.

perf: Move enrichment to accessors

---

rules/defense_evasion_process_injection.yml

Identifies the creation of a process with a parent process call stack not revealing normal API functions for process creation. This is a potential sign of process injection.

feat(rules): New `Process spawned via remote thread` rule

---

pkg/pe/parser.go
pkg/symbolize/symbolizer.go
pkg/symbolize/symbolizer_test.go

When resolving the symbol name from the
export directory, if the function RVA is
outside export directory range or the export directory is empty, we don't fallback to Debug Help API for symbol resolution, as it wouldn't be able to
retrieve symbol information.
Additionally, the PE exports now also contain ordinal symbols.

perf(symbolizer): Improve export directory symbolization

---

rules/defense_evasion_process_injection.yml
rules/macros/macros.yml

Identifies access to a remote thread followed by changing the thread registers to possibly divert the execution flow to the malicious code.

feat(rule): New `Potential thread execution hijacking` rule

---

pkg/filter/rules_test.go
pkg/kevent/kevent_windows.go
pkg/kevent/kevent_windows_test.go

The FNV hash has proved to produce colliding hashes for various partial keys. Aside from this, various partial keys can be calculated by a simple sum operation.

fix: Rework partial key calculation

---

pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
pkg/filter/filter.go
rules/defense_evasion_process_injection.yml
rules/macros/macros.yml

This changeset introduces potential process injection via tainted memory section and suspicious DLL loaded via memory section mapping rules along with the file fields to extract the file key and the protection rights of the section view.

feat(rules): New `Process injection via section mapping` rules

---

rules/defense_evasion_hijack_execution_flow.yml
rules/macros/macros.yml

Identifies when a binary is copied to a directory and shortly followed by the loading of an unsigned DLL from the same directory. Adversaries may
opt for moving legitimate signed binaries to a random directory and use them to side-load a malicious library.

feat(rules): New `DLL Side-Loading via a copied binary` rule

---

rules/initial_access_phishing.yml

Identifies the Microsoft Office process writing an executable file type and the call stack reveals the file creation was originated from the Microsoft
Visual Basic for Applications module. This is a high indicator of initial access using malicious macro-enabled documents.

feat(rules): New `Executable file creation from a macro-enabled Microsoft Office document` rule

---

rules/defense_evasion_process_injection.yml

Add a couple of exceptions and consider unmap section view events only for view sizes over 4096 bytes.

chore(rules): Solidify process injection rules

---

rules/persistence_boot_or_logon_autostart_execution.yml

RID (Relative ID part of security identifier) hijacking allows an attacker with SYSTEM level privileges to covertly replace the RID of a low privileged account effectively making the low privileged account assume Administrator privileges on the next logon.

feat(rules): New `RID hijacking` rule

---

pkg/symbolize/symbolizer.go

When checking whether the PE exports are empty, include the condition to ensure the PE was parsed correctly.

fix(symbolizer): Check PE parse status in symbolizer

---

rules/initial_access_phishing.yml
rules/macros/macros.yml

Identifies the execution of the child process spawned by Microsoft Office parent process where the call stack contains the Visual Basic for Applications modules or suspicious symbols. This is a strong indicative of the presence of a weaponized macro-enabled document.

feat(rules): New `Process spawned from macro-enabled Microsoft Office document` rule

---

pkg/kevent/callstack.go
pkg/symbolize/symbolizer.go
rules/defense_evasion_process_injection.yml

Identifies manipulation of the thread context from unbacked memory region. This may be indicative of process injection. This PR also fixes the thread callstack summary and the symbolized PE exports condition.

feat(rules) New `Thread context set unbacked memory` rule

---

rules/initial_access_phishing.yml
rules/macros/macros.yml
rules/privilege_escalation_exploitation_for_privilege_escalation.yml

Identifies the execution of the Windows scripting interpreter spawning a Microsoft Office process to execute suspicious Visual Basic macro.

feat(rules): New `Macro execution via script interpreters` rule

---

pkg/filter/filter.go
rules/credential_access_os_credential_dumping.yml

The partials for bound field rules are populated by calculating the hash and attaching it to event metadata.

fix(rules-engine): Add partials for bound fields

---

rules/initial_access_phishing.yml

Identifies Microsoft Office processes dropping a file with suspicious extension and with the call stack indicating operations to save or load the file from an embedded OLE object.

feat(rules): New  `Suspicious Microsoft Office embedded object` rule

---

cmd/fibratus/app/rules/create.go
cmd/fibratus/app/rules/rules.go

A new subcommand `fibratus rules create` is added to streamline rules creation by quickly generating a template where rule ID, version, minimum engine version, and optionally some labels are automatically populated.

feat(cli): Rule template creation via CLI

---

rules/credential_access_suspicious_security_package_loaded_by_lsass.yml
rules/persistence_suspicious_port_monitor_loaded.yml

Identifies the loading of an unsigned DLL by the print spool service. Adversaries may use port monitors to run an adversary supplied DLL during system boot for persistence or privilege escalation.

feat(rules): New `Suspicious port monitor loaded` rule

---

rules/privilege_escalation_potential_privilege_escalation_via_phantom_dll_hijacking.yml

Identifies the loading of the phantom DLL that was previously dropped to the System directory. Adversaries may exploit this flow to escalate privileges by placing a custom version of the DLL and initiating the execution of an auto-elevated high integrity Windows native process.

feat(rules): New `Potential privilege escalation via phantom DLL hijacking` rule

---

pkg/fs/dev.go
pkg/fs/dev_test.go

This PR contains the logic for normalizing the file paths when running Fibratus inside the isolated environment, aka silo (Windows Sandbox).

fix(fs): Handle Windows Sandbox paths

---

rules/credential_access_remote_thread_creation_into_lsass.yml
rules/persistence_suspicious_persistence_via_registry_modification.yml

Identifies the creation of a remote thread in LSASS (Local Security And Authority Subsystem Service) by untrusted or suspicious processes. This may indicate attempts to execute code inside the LSASS process in preparation for credential stealing.

feat(rules): New `Remote thread creation into LSASS` rule

---

configs/fibratus.yml
internal/bootstrap/bootstrap.go
pkg/config/alertsender.go
pkg/config/config_windows.go
pkg/config/schema_windows.go
pkg/kevent/queue.go
pkg/kstream/consumer_windows.go

This new flag allows running Fibratus in event forwarding mode. When in event forwarding mode, the rule engine is disabled and all events are routed to the output sink.

fest: Introduce event forwarding mode flag

---

pkg/kevent/queue_test.go

Refactor the event queue pushing test under the presence of the `enqueAlways` condition.

fix(test): Correct event queue push tests

---

pkg/util/version/version.go

Dev versions can be flagged with an empty string or the `0.0.0` pseudo version string. `dev` is never a valid version.

fix: Adjust `dev` version identifier

---

.github/workflows/master.yml
.github/workflows/pr.yml
.github/workflows/release.yml

Upgrades cache, upload-artifact, and setup-go actions to use a newer Node version.

ci(workflows): Upgrade deprecated actions

---

pkg/util/log/logger.go

Disables quoting for all values in log lines. The result is that all control chars (new line, tabs, etc.) are rendered instead of escaped which greatly improves the log message readability.

chore(log): Disable quoting for all values

---

pkg/filter/action/emit.go

When the rule is fired, besides including the alert name and text, the list of all events that triggered the alert is also included in the log message.

chore(rule-engine): Dump events in rule matches

---

build/msi/fibratus.wxs

The Systray component missed the `Directory `attribute resulting in the fibratus-systray.exe binary being placed within the root directory instead of the `Bin `directory.

fix(msi): Attach BINDIR to Systray component

---

internal/bootstrap/bootstrap.go
pkg/config/print.go
pkg/util/version/version.go

Dump fibratus version to logs. Having the version in the logs may help during troubleshooting or identitying bugs that are specific to the certain release.

chore: Show fibratus version in logs

---

rules/privilege_escalation_vulnerable_or_malicious_driver_dropped.yml

Introduce `file.is_driver` condition to stop evaluating the subsequent conditions inside the paren expression as they may consume unneeded CPU cycles.

perf(rules): Improve `Vulnerable or malicious driver dropped` rule

---

rules/defense_evasion_potential_thread_execution_hijacking.yml
rules/macros/macros.yml

To foster reusability, the expression for detecting remote thread access is extracted into a macro.

chore(rules): Introduce `open_remote_thread` macro

---

rules/credential_access_potential_sam_hive_dumping.yml

Only keep a single registry key path for detecting potential accesses to the Security Account Manager database.

chore(rules): Reduce `Potential SAM hive dumping` false positives

---

pkg/config/alertsender.go

If the capture is set in the configuration flags, either the capture is being generated or replayed. In a such scenario, alert senders are useless and should be disabled.

fix(kcap): Disable alert senders in capture replay mode

---

pkg/alertsender/slack/slack.go

Compose attachment text with alert title and text. Adjust attachment color for high-severity alerts.

fix(alertsender,slack): Compose attachment text with alert title and text

---

pkg/yara/scanner.go
pkg/yara/scanner_test.go

Adding yara scan trigger for PAGE_EXECUTE_READWRITE allocations, useful when PE image does not contain malicious code, for example, when shellcode is downloaded or decrypted after execution

feat(yara): Adding yara scan trigger for PAGE_EXECUTE_READWRITE allocations

---

.github/workflows/release.yml

This was overlooked from the previous commit and the set-output directive was only removed in the slim build job.

ci(workflows): Address `set-output` deprecation

---

pkg/alertsender/renderer/renderer_test.go
pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
pkg/filter/filter_test.go
pkg/kevent/batch_test.go
pkg/kevent/kevent_windows.go
pkg/kevent/kparam_windows.go
pkg/kevent/kparams/fields_windows.go
pkg/kevent/marshaller_test.go
pkg/kevent/marshaller_windows.go
pkg/outputs/amqp/amqp_test.go
pkg/outputs/elasticsearch/elasticsearch_test.go
pkg/outputs/eventlog/eventlog_test.go
pkg/outputs/http/http_test.go
pkg/ps/snapshotter_windows.go
pkg/ps/snapshotter_windows_test.go
pkg/ps/types/types_windows.go
pkg/symbolize/symbolizer_test.go
pkg/yara/scanner_test.go

This changeset factors out the `entrypoint` parameter name and the `thread.entrypoint` filter name. More precisely, the filter name is superseded by `thread.start_address`.
Yes. The new filter name, `thread.start_address` should be reflected in the docs.

refactor(event,filter): Rename thread entrypoint parameter

---

configs/fibratus.yml
pkg/alertsender/eventlog/config.go
pkg/alertsender/eventlog/eventlog.go
pkg/alertsender/eventlog/eventlog_test.go
pkg/alertsender/sender.go
pkg/config/alertsender.go
pkg/config/config_windows.go
pkg/config/config_windows_test.go
pkg/config/schema_windows.go

The eventlog alertsender emits the alerts to the
eventlog. By default, the message is a combination of alert title and text. The severity of the eventlog message is determined by the alert severity. The eventlog alert sender is enabled by default.
> Mark the option with the `x` symbol inside the brackets. Trim leading/trailing white spaces. Remove any options that don't apply to your changeset.
> Mark the option with the `x` symbol inside the brackets. Trim leading/trailing white spaces. Remove any options that don't apply to your changeset.
The …

feat(alertsender): Introduce eventlog alertsender

---

pkg/kevent/flags.go
pkg/kevent/flags_test.go
pkg/kevent/kparam_windows.go
pkg/kevent/kparams/fields_windows.go

Process rundown, create, and terminate events are enriched with additional flags that may indicate if the created process is WoW-originated, protected, or packaged.
The process flags parameter needs to be reflected in the documentation. The parameter will serve as a backbone for building the new filter fields.

feat(event): Augment process events with process flags

---

pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
rules/defense_evasion_regsvr32_scriptlet_execution.yml
rules/defense_evasion_system_binary_proxy_execution_via_rundll32.yml

Introduce a new filter field `ps.child.pe.file.name` that is uniform with the other `ps.child.*` fields.
Yes. The fields documentation needs to be updated to express the usage preference of the new filter field.

refactor(filter,rules): Deprecate pe.ps.child.file.name field

---

pkg/kevent/sequencer_windows.go
pkg/kevent/sequencer_windows_test.go

Make sure the sequencer registry value is
reset before running the tests. This implies
handling the return value of the DeleteValue
function to ignore the error if the sequencer
is trying to remove a non-existing value.

fix(tests): Revive event sequencer tests

---

internal/etw/source_test.go

Leftovers from the event source refactoring caused the stack enrichment tests to fail, as the test binary name was pointing to the previous one.

fix(tests): Correct expected test binary in the stack frame

---

rules/defense_evasion_appdomain_manager_injection_via_clr_search_order_hijacking.yml

Adversaries can abuse the CLR search order to load the malicious assembly from a writable directory by simply following the assembly file naming conventions and ensuring the .NET LOBIN is executed with the right environment variables set.

feat(rules): New `AppDomain Manager injection via CLR search order hijacking` rule

---

rules/defense_evasion_dotnet_assembly_loaded_by_unmanaged_process.yml

Identifies the loading of the .NET assembly by unmanaged process. Adversaries can load the CLR runtime inside an unmanaged process and execute the assembly via the `ICLRRuntimeHost::ExecuteInDefaultAppDomain` method.

feat(rules): New `.NET assembly loaded by unmanaged process` rule

---

pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
pkg/filter/filter_test.go
pkg/ps/snapshotter_windows.go
pkg/ps/snapshotter_windows_test.go
pkg/ps/types/types_windows.go
pkg/sys/process.go
pkg/sys/syscall.go
pkg/sys/zsyscall_windows.go

This PR adds a new set of filter fields that identify if the child, parent, or the process generating the event are WOW64, packaged, or protected processes.
---
> /kind design
---
/area …

feat(filter, proc): Process flags filter fields

---

configs/fibratus.yml
pkg/alertsender/alert.go
pkg/alertsender/mail/config.go
pkg/alertsender/mail/mail.go
pkg/alertsender/mail/renderer.go
pkg/alertsender/mail/renderer_test.go
pkg/alertsender/mail/template.go
pkg/config/schema_windows.go
pkg/filter/action/emit.go

HTML templates are more likely to exclusively be used by the mail sender. For this purpose, a new config flag is defined that determines if the alert is sent with HTML template or plain text. Alert structure is augmented with labels and description fields to make it compatible with the same fields available in the filter config.
The new email sender config flag dictates if the HTML template is used to render the alert or either a plain-text format.

refactor(alertsenders/mail): Move template rendering to sender

---

internal/etw/processors/processor.go
pkg/pe/parser.go

Slices the data buffer returned by the NTFS parser read operation. Additionally, prevent parsing the PE byte buffer if it is empty.

fix(processors, pe): Improve NTFS parser error handling

---

go.mod
go.sum
pkg/pe/parser.go

Besides bumping the `saferwall/pe` dependency, a couple of other changes are introduced in this PR. Firstly, the certificate structure is adapted to only consult the first certificate. This could change in the future if we wanted to grab the entire certificate chain. The second change concerns routing the `saferwall/pe` log messages to logrus.

chore(deps, pe): Bump `saferwall/pe` from 1.4.4 to 1.5.4

---

internal/etw/processors/fs_windows.go

Correct the condition to only increment missing file object lookups if the request is coming from non-CloseFile event.

fix(eventsource,etw): Correct file object lookup misses expvar

---

cmd/fibratus/app/rules/validate.go
pkg/config/filters.go

When the rule definition misses the recommended `MITRE` labels, declare the warning with the missing label.
Users will be able to spot rule validation warnings when any of the recommended tactic/technique labels are missing in the rule definition.

chore(cli): Surface missing labels in rules validation subcommand

---

internal/bootstrap/bootstrap.go
internal/bootstrap/config.go

If the YAML config contains malformed content the
error is ignored silently. To prevent this, we
only proceed with default settings loading if the
config file doesn't exist. On the contrary, the
error is raised.

fix(config): Prevent loading malformed yaml

---

rules/persistence_rid_hijacking.yml

If the registry set value is initiated by the LSASS process, we can assume it is a false positive.
---
> /kind design
---
> /area yara
> /area event
> /area …

fix(rules): Reduce `RID Hijacking` rule false positives

---

pkg/kcap/version/version_windows.go
pkg/kevent/marshaller_windows.go
pkg/ps/types/marshaller_windows.go
pkg/ps/types/marshaller_windows_test.go

The process state marshaller stores the new
`IsWow64`,  `IsPackaged`, and  `IsProtected` fields
into the binary blob.
---
> /kind design
---
> /area yara
> /area event
/area …

chore(kcap): Persist process flags in capture

---

rules/defense_evasion_potential_injection_via_dotnet_debugging.yml

Identifies creation of a process on behalf of the CLR debugging facility which may be indicative of code injection. The CLR interface utilizes the OpenVirtualProcess method to attach the debugger to the remote process.
---
> /kind design
---
> /area …

feat(rules): New `Potential injection via .NET debugging` rule

---

rules/persistence_hidden_local_account_creation.yml

Identifies the creation of a hidden local account. Adversaries can create hidden accounts by appending the dollar sign to the account name. This technique renders the account name hidden to user enumeration tools such as net user and effectively bypasses detections.
---
> /kind design
---
> …

feat(rules):  New `Hidden local account creation` rule

---

pkg/ps/snapshotter_windows.go
pkg/sys/process.go

Fixes spurious conditions when querying process protection attributes.
---
> /kind design
---
> /area yara
> /area event
> …

fix(proc): Spurious conditions when querying process protection attributes

---

pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
pkg/filter/filter_test.go
pkg/fs/file_class.go
pkg/kevent/kparam.go

This PR introduces a set of filter fields that permit extracting the file information class and the scalar values pertaining to the Allocation, EOF, and Disposition information classes. More specifically, the following fields are added:
- `file.info_class`: identifies the file information class present in `SetFileInformation`, `DeleteValue`, and `RenameFile` events.
- `file.info.allocation_size`: represents the file allocation size
- `file.info.eof_size`: represents the file EOF (End Of File) size
- `file.info.is_disposition_file_delete`: indicates if the file is deleted when its handle is closed
---
> /kind refactor …

feat(filter): Add additional file filter fields

---

rules/defense_evasion_dll_loaded_via_callback_function.yml

Identifies module proxying as a method to conceal suspicious callstacks. Adversaries use module proxying the hide the origin of the LoadLibrary call from the callstack by loading the library from the callback function.
---
> /kind design
---
> /area …

feat(rules): New `DLL loaded via a callback function` rule

---

rules/defense_evasion_process_execution_from_self_deleting_binary.yml
rules/macros/macros.yml

Identifies the execution of the process from a self-deleting binary. The attackers can abuse undocumented API functions to create a process from a file-backed section. The file is put into a delete-pending state allowing the attacker to bypass kernel callback controls by closing the handle to the file before the main thread is spawned.
---
> /kind design
> /kind …

feat(rules): New `Process execution from a self-deleting binary` rule

---

rules/defense_evasion_image_load_via_ntfs_transaction.yml

Identifies image loading of a file written to disk via NTFS transaction. Adversaries may exploit the transactional API to execute code in the address space of the running process without committing the code to disk.
---
> /kind design
---
> /area …

feat(rules): New `Image load via NTFS transaction` rule

---

rules/defense_evasion_dll_loaded_via_apc_queue.yml

Identifies loading of a DLL with a callstack originating from the thread alertable state that led to the execution of an APC routine. This may be indicative of sleep obfuscation or process injection attempt.
---
> /kind design
---
> /area …

feat(rules): New `DLL loaded via APC queue` rule

---

rules/defense_evasion_hidden_registry_key_creation.yml

Identifies the creation of a hidden registry key. Adversaries can utilize the native `NtSetValueKey` API to create a hidden registry key and conceal payloads or commands used to maintain persistence.
---
> /kind design
---
> …

feat(rules): New `Hidden registry key creation` rule

---

internal/etw/processors/registry_windows.go

If the registry value is found within the hidden
key, skip reading the value as it would inevitably fail.
---
> /kind design
---
> /area yara
> /area event
> …

fix(processors): Skip reading value for hidden registry keys

---

internal/etw/processors/fs_windows.go

The file metainfo should be removed only by the file object. Doing this also by file key can lead to evicting file info that is used by subsequent events to derive the file name.
---
> /kind design
---
> /area …

fix(processors): Release file only by file object

---

pkg/yara/scanner.go
pkg/yara/scanner_test.go

Log the loading of the YARA rule and check the size of the view of section. Small sections should not be
candidates for scanning.
---
> /kind design
---
/area yara
> /area …

chore(yara): Log rule loading and check view section size

---

rules/defense_evasion_clear_eventlog.yml
rules/macros/macros.yml

Identifies attempts to clear Windows event log stores. Adversaries attempt to evade detection or destroy forensic evidence on a system to cover their trails and slow down incident response.
---
> /kind design
---
> /area …

feat(rules): New `Clear Eventlog` rule

---

configs/fibratus.yml
pkg/alertsender/eventlog/config.go
pkg/alertsender/systray/config.go
pkg/config/_fixtures/fibratus.yml

Disable the systray alert sender by default, and enable evenlog verbose mode.
---
> /kind design
---
> /area yara
> /area event
/area alertsenders
> /area …

chore(alertsenders): Disable systray alertsender by default

---

rules/credential_access_potential_sam_hive_dumping.yml
rules/defense_evasion_dotnet_assembly_loaded_by_unmanaged_process.yml
rules/defense_evasion_hidden_registry_key_creation.yml
rules/defense_evasion_potential_process_hollowing_injection.yml
rules/defense_evasion_potential_process_injection_via_tainted_memory_section.yml
rules/defense_evasion_potential_thread_execution_hijacking.yml
rules/defense_evasion_thread_context_set_from_unbacked_memory.yml
rules/defense_evasion_unsigned_dll_injection_via_remote_thread.yml
rules/initial_access_macro_execution_via_script_interpreter.yml

Make the rules less noisy by adding various conditions to prevent false positives. Also, reformat some rules for better readability.
---
> /kind design
---
> /area yara
> /area …

chore(rules): Eliminate false positives in process injection rules

---

pkg/pe/parser.go

The CLR parsing logic relies on the presence
of the section headers. Enable section parsing
if CLR option is present.
---
> /kind design
---
> /area yara
> /area event
> /area …

fix(pe): Require sections during CLR parsing

---

rules/credential_access_lsass_memory_dumping.yml

Certain tools tend to duplicate the lsass process
token and then initiate the minidump creation.
---
> /kind design
---
> /area yara
> /area event
> /area …

chore(rules): Consider DUP_HANDLE access right

---

rules/defense_evasion_dll_sideloading_via_copied_binary.yml
rules/defense_evasion_potential_process_hollowing_injection.yml

Make sure the not operator is placed after the field.
---
/kind cleanup
> /kind design
---
> /area yara
> /area event
/area rules
> …

chore(rules): Reorder not operators

---

internal/bootstrap/bootstrap.go
pkg/util/log/logger.go

Firstly, make sure the file exists before
we try to get the handle to it. Secondly,
duplicate the file handle and pass it to
SetStdHandle.
---
> /kind design
---
> /area yara …

fix(log): Panic redirection to logs

---

go.mod
go.sum
pkg/pe/parser.go

CLR metadata parsing is not considered useful
for detection purposes so we can safely disable
it and gain some perf improvements.
---
> /kind design
---
> /area yara
> /area …

perf(pe): Disable CLR metadata parsing

---

pkg/yara/config/config.go
pkg/yara/scanner.go

If the process is performing many VirtualAlloc calls
with RWX page protection, and one call results in a rule
match, then we don't need to repeatedly initiate the
scan for the same process.
---
> /kind design
--- …

chore(yara): Virtual alloc rwx once per process

---

rules/defense_evasion_clear_eventlog.yml
rules/defense_evasion_hidden_registry_key_creation.yml
rules/defense_evasion_potential_process_hollowing_injection.yml
rules/defense_evasion_potential_process_injection_via_tainted_memory_section.yml
rules/defense_evasion_thread_context_set_from_unbacked_memory.yml
rules/defense_evasion_unsigned_dll_injection_via_remote_thread.yml
rules/persistence_script_interpreter_or_untrusted_process_persistence.yml

Reduces false positives in the following rules.
- Thread context set from unbacked memory: include the taskhostw.exe exception
- Hidden registry key creation: Make sure the callstack contains the *SetValueKey symbol
- Hidden registry key creation: include explorer.exe exception
- Potential process injection via tainted memory section: discard all processes from the Program Files/Program Files (x86) directories
- Script interpreter host or untrusted process persistence: include msedge.exe exceptions
Demotes the severity to medium in the Clear Eventlog rule.
---
/kind refactor (non-breaking change that restructures the code, while …

chore(rules): Reduce false positives

---

pkg/kevent/kparams/fields_windows.go
pkg/symbolize/symbolizer.go

Resolve the thread start address to its respective symbol name and the module from which the function call is originated.
---
> /kind design
---
> /area yara
> /area event
> …

feat(symbolizer): Symbolize thread start address

---

internal/etw/processors/image_windows.go
internal/etw/processors/image_windows_test.go
internal/etw/source_test.go
pkg/kcap/reader_windows.go
pkg/ps/snapshotter.go
pkg/ps/snapshotter_mock.go
pkg/ps/snapshotter_windows.go
pkg/ps/snapshotter_windows_test.go
pkg/ps/types/types_windows.go

Instead of appending/removing the process modules
by their image name, we're now using the module base address to determine if it was already added. The same logic is used to remove the existing module.
---
> /kind design
---
> …

chore(ps): Append/remove module by base address

---

pkg/filter/ql/expr.go
pkg/filter/ql/literal.go

`fmt.Sprintf` exhibits poor performance, especially when used in hot paths. To overcome this deficiency, we use the StringBuilder for a more efficient string concatenation.
---
> /kind design
---
/area …

perf(filter): Speed up expression String methods

---

pkg/filter/filter_test.go
pkg/filter/ql/ast.go
pkg/filter/ql/token.go
pkg/util/sets/intersection.go
pkg/util/sets/intersection_test.go

The intersects operator and its case-insensitive variant, operate on string slices. If all elements in the RHS slice are present in the slice given by LHS, the operator evaluates to true. Otherwise, it evaluates to false.
---
> /kind design
---
> /area …

feat(filter): Intersects operator

---

internal/etw/source_test.go
pkg/kevent/flags.go
pkg/kevent/kparam_windows.go

The callstack is included in the event parameters. For the sake of performance, we're deriving the callstack only for the interesting flag set.
---
> /kind design
---
> /area …

feat(event): Callstack for OpenProcess/OpenThread events

---

pkg/filter/filter_test.go
pkg/kevent/callstack.go
pkg/sys/mem.go
pkg/sys/syscall.go
pkg/sys/zsyscall_windows.go
pkg/util/va/region.go
pkg/util/va/region_test.go

Attackers exploit the memory of the benign module (dll) to inject their own shellcode. When the memory of the DLL is tampered, the backing memory pages release the shared attribute and become private pages. If the callstack contains such memory regions, it is a strong indicator of module stomping.
To accomplish the detection of stomped modules, we use the `QueryWorkingSet` API to examine the pages starting from the stack return address. If the `Shared` or `SharedOriginal` bits are not set, we increment the private allocation size by OS page size.
---
> /kind refactor (non-breaking change that restructures the code, while not …

fix(callstack): Fix private allocation size

---

rules/macros/macros.yml

Include registry paths that adversaries can use to run programs to automatically launch at boot.
---
> /kind design
---
> /area yara
> /area event
> /area …

chore(rules): Expand registry persistence keys list macro

---

rules/credential_access_lsass_memory_dump_via_wer.yml

On some occasions, the process name is reported in lowercase, preventing the rule matching. In the
Similarly, to improve resilience, the `create_file `macro is used in the second condition to match when the `WER` process creates the memory dump.
---
> /kind design
---
> Uncomment one or more …

fix(rules): Use iin operator in LSASS memory dump via Windows Error Reporting rule

---

.github/workflows/master.yml
.github/workflows/pr.yml
.github/workflows/release.yml
make.bat

Python 3.7 was removed from the Windows Server 2022 image, so we must set it up manually. Also, fail if the compilation doesn't succeed to make CI red.
---
> /kind design
--- …

fix(build, ci): Bring Python in CI

---

rules/defense_evasion_appdomain_manager_injection_via_clr_search_order_hijacking.yml
rules/defense_evasion_dotnet_assembly_loaded_by_unmanaged_process.yml
rules/defense_evasion_hidden_registry_key_creation.yml
rules/defense_evasion_potential_injection_via_dotnet_debugging.yml

To improve rules efficacy against false positives, we ensure the process has a valid state by checking the process executable path.
In `Hidden registry key creation` rule, add the exception for the `lsass.exe` process.
---
> /kind design
---
> /area …

fix(rules): Improve rules efficacy against false positives

---

pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
pkg/filter/filter_test.go

Incorporate the new `thread.start_address.symbol` and `thread.start_address.module`  fields to extract the symbol corresponding to the thread start address and its module respectively.
---
> /kind design
---
> …

feat(filter): Add start address symbol and module fields

---

pkg/filter/accessor_windows.go
pkg/filter/fields/fields.go
pkg/filter/fields/fields_windows.go
pkg/filter/filter_test.go
pkg/filter/ql/function.go
pkg/filter/util.go
pkg/kevent/callstack.go
pkg/kevent/callstack_test.go
pkg/symbolize/symbolizer.go
pkg/util/va/address.go

The new filter fields allow accessing the attributes of the last user/kernel space frame. Additionally, symbols/module filter fields are modified to accept an optional frame index argument and only retrieve the symbol/module name of the accessed frame. The callstack segments are added to access the signature info of the iterated frame.
---
> /kind design
> /kind …

feat(filter): Add additional callstack fields

---

go.mod
go.sum
internal/etw/processors/fs_windows.go
pkg/kevent/callstack.go
pkg/kevent/callstack_test.go
pkg/kevent/queue.go

Keep the stack walk events indexed by stack id. The stack id is a tuple of pid,tid associated with the thread executing the code. For every unique stack id, the queue of pending events is maintained. When the corresponding stack walk event arrives, the oldest event is pulled from the queue and enriched with stack addresses.
---
> /kind design
> /kind other (change that …

refactor(event): Improve callstack decorator

---

rules/defense_evasion_process_execution_from_self_deleting_binary.yml

Adding an exclusion to the defense_evasion_process_execution_from_self_deleting_binary.yml rule in order to prevent false positives from Windows updates. 
Adding the following path exclusion: '?:\\Windows\\SoftwareDistribution\\Download\\*'
---
> /kind design
---
> Uncomment one or more `/area …

fix(rule): Add exclusion for `Process execution from a self-deleting binary` rule

---

pkg/symbolize/symbolizer.go
pkg/symbolize/symbolizer_test.go

Keep all resolved symbols in the map indexed by pid and return address. Before entering the address symbolisation path, consult the cached symbols. If the symbol is already resolved, we can skip the costly symbolisation process.
---
> /kind design
--- …

perf(symbolizer): Speed up symbol resolution

---

pkg/callstack/callstack.go
pkg/callstack/callstack_test.go
pkg/filter/accessor_windows_test.go
pkg/filter/filter_test.go
pkg/filter/ql/function.go
pkg/kevent/formatter.go
pkg/kevent/formatter_windows.go
pkg/kevent/kevent.go
pkg/kevent/kevent_windows_test.go
pkg/kevent/queue.go
pkg/kevent/stackwalk.go
pkg/kevent/stackwalk_test.go
pkg/symbolize/symbolizer.go

The mechanics revolving around callstack parsing and processing are growing significantly. To avoid this growth undermining mantainability, move all callstack-related stuff into a separate package.
---
> /kind design
---
> /area …

refactor(callstack): Move callstack into independent package

---

rules/credential_access_potential_sam_hive_dumping.yml
rules/defense_evasion_dotnet_assembly_loaded_by_unmanaged_process.yml
rules/defense_evasion_process_execution_from_self_deleting_binary.yml
rules/defense_evasion_unsigned_dll_injection_via_remote_thread.yml

This PR introduces various exclusions to keep false positives under control.
---
> /kind design
---
> /area yara
> /area event
> /area …

fix(rules): Add exclusions to reduce false positives

---

pkg/filter/ql/functions/substr.go
pkg/filter/ql/functions/substr_test.go

Make the `substr` function optionally accept the third argument. If the third argument is not given, the string is sliced from the start index to its length.
---
> /kind design
---
/area …

chore(function): `substr` function with optional argument

---

pkg/yara/scanner.go

If the suspicious section of view mapping already produced a rule match for the process, we don't keep running the scans for that process.
---
> /kind design
---
/area yara
> …

perf(yara): Limit YARA mmap scans

---

internal/etw/processors/registry_windows.go
internal/etw/source.go
internal/etw/source_test.go
internal/etw/trace.go
pkg/kevent/ktypes/ktypes_windows.go
pkg/kevent/ktypes/ktypes_windows_test.go
pkg/sys/etw/types.go

After exhaustive triaging, it was spotted that the system registry provider can miss stackwalk samples. This can have disastrous consequences such as wrongly attributing stack return addresses or accumulated events. To elegantly mitigate the problem, we enable the registry flags on the system logger and receive all events within the same session. As a result, the Registry System Logger session/consumer are eliminated.
--- …

chore(telemetry): Ditch registry system provider

---

pkg/rules/engine.go

To prevent data race behaviors, protect the rule matches slice with a mutex.
---
> /kind design
---
> /area yara
> /area event
> /area …

fix(rule-engine): Guard rule matches slice with mutex

---

cmd/fibratus/app/stats/stats.go
pkg/kevent/stackwalk.go
pkg/kevent/stackwalk_test.go

This PR improves the `expvar` counters for various stackwalk decorator statistics.
---
> /kind design
---
> /area yara
> /area event
> …

chore(callstack): Better expvar insights for stackwalk decorator

---

pkg/rules/action/isolate_windows.go

This PR brings various changes to the `isolate` action. The first of them is declaring the WFP session as dynamic, Dynamic sessions are meant to add firewall configuration that should not outlast the program's execution. The second fix prevents the deadlock on mutex when adding whitelist IP addresses. Lastly, The current limitation of the `fw` library, makes it impossible to install a filter with multiple IP addresses, so we shrink the list to always append the first IP address in the list.
---
> /kind breaking (fix or …

fix(action): Fix isolate action

---

pkg/filter/accessor.go
pkg/filter/accessor_windows.go
pkg/filter/fields/fields_windows.go
pkg/filter/filter_test.go
pkg/filter/filter_windows.go
pkg/filter/ql/function.go

This changeset brings the implementation of the thread pool field accessor.
---
> /kind design
---
/area filters
> /area yara
> /area event
> /area …

feat(filter): Thread pool filter fields

---

rules/defense_evasion_potential_process_injection_via_tainted_memory_section.yml

Reduce false positives by adding exceptions for the process executables.
---
> /kind design
---
> /area yara
> /area event
> /area …

fix(rules): Add process executable exceptions for `Potential process injection via tainted memory section` rule

---

rules/credential_access_credential_discovery_via_vaultcmd.yml
rules/credential_access_lsass_memory_dump_preparation_via_silent_process_exit.yml
rules/credential_access_suspicious_security_package_loaded_by_lsass.yml
rules/credential_access_unusual_access_to_ssh_keys.yml
rules/credential_access_unusual_access_to_web_browser_credential_stores.yml
rules/credential_access_unusual_access_to_windows_credential_history.yml
rules/defense_evasion_dll_sideloading_via_copied_binary.yml
rules/defense_evasion_process_spawned_via_remote_thread.yml
rules/initial_access_executable_file_creation_from_macro_enabled_microsoft_office_document.yml
rules/initial_access_macro_execution_via_script_interpreter.yml
rules/initial_access_process_spawned_from_macro_enabled_microsoft_office_document.yml
rules/initial_access_suspicious_microsoft_office_embedded_object.yml
rules/persistence_network_connection_via_startup_folder_executable_or_script.yml
rules/persistence_script_interpreter_or_untrusted_process_persistence.yml
rules/persistence_suspicious_startup_shell_folder_modification.yml
rules/persistence_unusual_process_modified_registry_run_key.yml

Format rule conditions for consistency and improved readability.
---
> /kind design
---
> /area yara
> /area event
/area …

chore(rules): Format rule conditions

---

pkg/rules/engine.go
pkg/rules/sequence.go
pkg/rules/sequence_test.go

Events can arrive in non-deterministic order since they are published by independent providers. The side effect of this can translate in the form of a missing process state. Imagine the `OpenProcess` event arriving from the process before the process's own creation event. To mitigate this bad behavior, we always check the process state before evaluating out-of-order events.
---
> /kind …

fix(rule-engine): Check process state before evaluation

---

rules/defense_evasion_suspicious_object_symbolic_link_creation.yml
rules/macros/macros.yml

Identifies the creation of the object symbolic link inside the object manager namespace by untrusted or unusual processes. Adversaries may exploit object symbolic links to trick system processes into executing malicious payloads.
---
> /kind design
--- …

feat(rules): New `Suspicious object symbolic link creation` rule

---

rules/defense_evasion_potential_process_hollowing_injection.yml

Added an exclusion for OneDrive to tune false positives on this rule to reduce false positives
---
kind improvement
> /kind design
---
> /area yara
> /area event
> /area …

fix(rules): Exclusion for OneDrive to tune false positives in `Potential process hollowing` rule

---

pkg/symbolize/symbolizer.go
pkg/sys/process.go
pkg/sys/process_test.go

When the module in process state can't be derived from the VA, we enumerate the modules via an API call and try to resolve
the module.
---
> /kind design
---
> /area yara
> …

fix(symbolizer): Lookup live modules

---

pkg/filter/filter.go
pkg/filter/filter_test.go

Allow interpolation for fields with underscore characters.
---
> /kind design
---
/area filters
> /area yara
> /area event
> /area rules …

fix(filter): Allow interpolation for fields with underscore characters

---

rules/credential_access_lsass_memory_dump_via_minidumpwritedump.yml

Identifies access to the Local Security Authority Subsystem Service (LSASS) process to dump the memory via MiniDumpWriteDump API.
---
> /kind design
---
> /area yara
> /area …

feat(rules): New `LSASS memory dump via MiniDumpWriteDump` rule

---

rules/initial_access_potential_clickfix_infection_chain_via_run_window.yml

Identifies the execution of the process via the `Run` command dialog box followed by a network connection. This could be indicative of the `ClickFix` deceptive tactic used by attackers to lure victims into executing malicious commands under the guise of meeting pages or CAPTCHAs.
---
> /kind design
> /kind other (change that doesn't pertain to any of the above …

feat(rules): New `Potential ClickFix infection chain via Run window` rule

---

rules/credential_access_lsass_handle_leak_via_seclogon.yml

Identifies suspicious access to LSASS process from a callstack pointing to seclogon.dll that may indicate an attempt to leak an LSASS handle via abusing the Secondary Logon service in  preparation for credential access.
---
> /kind design
---
> /area …

feat(rules): New `LSASS handle leak via Seclogon` rule

---

rules/persistence_unusual_process_modified_registry_run_key.yml

Added CompatTelRunner.exe as an exclusion to reduce false positives on this rule.
---
kind improvement
> /kind design
---
> /area yara
> /area event
> …

fix(rules): Add `CompatTelRunner.exe` as an exclusion in `Unusual process modified registry run key` rule

---

rules/persistence_script_interpreter_or_untrusted_process_persistence.yml

To have better exclusions for false positive tuning, and changed the name/description.
---
kind improvement
> /kind design
---
> /area yara
> /area event …

chore(rules): Improve `Script interpreter host or untrusted process persistence` rule

---

rules/defense_evasion_unsigned_dll_injection_via_remote_thread.yml

To make the rule more resistant to false positives, add the condition to evaluate the symbol pertaining to the thread start address.
---
> /kind design
---
> /area yara
> …

chore(rules): Improve `Unsigned DLL injection via remote thread` rule

---

rules/defense_evasion_dll_loaded_via_ldrpkernel32_overwrite.yml

Detects attempts to bypass the standard NTDLL bootstrap process by loading a malicious DLL early through hijacking. The malicious DLL, containing attacker-controlled code, is loaded in place of the legitimate kernel32 DLL.
---
> /kind design
---
> …

feat(rules): New `DLL loaded via LdrpKernel32 overwrite` rule

---

rules/credential_access_lsass_access_from_unsigned_executable.yml
rules/macros/macros.yml

Detects attempts by an unsigned process to access the Local Security Authority Subsystem Service (LSASS). Adversaries may try to dump credential information stored in the process memory of LSASS.
---
> /kind design
---
> /area …

feat(rules): New `LSASS access from unsigned executable` rule

---

rules/persistence_suspicious_netsh_helper_dll_execution.yml

Identifies the execution of a suspicious Netsh Helper DLL. Adversaries may establish persistence by executing malicious content triggered by Netsh Helper DLLs. Netsh.exe is a command-line scripting utility used to interact with the network configuration of a system. It supports the addition of custom DLLs to extend its functionality that attackers can weaponize.
---
> /kind design
> /kind …

feat(rules): New `Suspicious Netsh Helper DLL execution` rule

---

rules/defense_evasion_potential_shellcode_execution_via_etw_logger_thread.yml

Adversaries may employ the undocumented EtwpCreateEtwThread function to execute shellcode within the local process address space.
---
> /kind design
---
> /area yara
> /area …

feat(rules): New `Potential shellcode execution via ETW logger thread` rule

---

pkg/callstack/callstack.go
pkg/callstack/callstack_test.go
pkg/filter/filter_test.go
pkg/kevent/kevent_windows_test.go

Change the heuristics for obtaining the final user code stack frame by looking for the presence of modules that do not reference Win32 or Native (ntdll) layers that are intermediary modules for transitioning into kernel land.
---
> /kind design
---
> …

fix(callstack): Rework final user frame heuristics

---

rules/initial_access_suspicious_execution_via_wmi_from_microsoft_office_process.yml

Identifies a suspicious process execution via Windows Management Instrumentation (WMI) originated from the Microsoft Office process loading an unusual WMI DLL. This technique can indicate code execution evading traditional parent/child processes spawned from Microsoft Office products.
---
> /kind design
> /kind other (change that doesn't pertain to any of the above …

feat(rules): New `Suspicious execution via WMI from a Microsoft Office process` rule

---

rules/credential_access_lsass_process_clone_creation_via_reflection.yml

Identifies the creation of an LSASS clone process via `RtlCreateProcessReflection` API function. Adversaries can use this technique to dump credentials material from the LSASS fork and evade defenses.
---
> /kind design
---
> …

feat(rules): New `LSASS process clone creation via reflection` rule

---

rules/defense_evasion_potential_process_creation_via_shellcode.yml

Identifies the creation of a process with stack frames originating from floating memory area while invoking commonly used Windows API functions like `WinExec`. This behavior is a typical indicator of code injection employing offensive shellcode maneuvering.
---
> /kind design
---
> Uncomment …

feat(rules): New `Potential process creation via shellcode` rule

---

rules/defense_evasion_suspicious_xsl_script_execution.yml

Identifies a suspicious execution of XSL script via Windows Management Instrumentation command line tool or XSL transformation utility. Adversaries may bypass application control and obscure the execution of code by embedding scripts inside XSL files. Extensible Stylesheet Language (XSL) files are commonly used to describe the processing and rendering of data within XML files.
---
> /kind …

feat(rules): New `Suspicious XSL script execution` rule

---

rules/defense_evasion_suspicious_html_application_script_execution.yml

Identifies the execution of scripts via Microsoft HTML Application Host interpreter. Adversaries can proxy the execution of arbitrary script code through a trusted, signed utility to evade defenses.
---
> /kind design
---
> …

feat(rules): New `Suspicious HTML Application script execution` rule

---

rules/persistence_suspicious_port_monitor_loaded.yml
rules/persistence_suspicious_print_processor_loaded.yml

Identifies when the print spooler service loads unsigned or untrusted DLL and the callstack pattern indicates the print processor is loaded. Adversaries may abuse print processors to run malicious DLLs during system boot for persistence and/or privilege escalation.
---
> /kind design
---
> …

feat(rules): New `Suspicious print processor loaded` rule

---

rules/credential_access_suspicious_vault_client_dll_load.yml

Identifies loading of the Vault client DLL by an unusual process. Adversaries can abuse the functions provided by the Credential Vault Client Library to enumerate or harvest saved credentials.
---
> /kind design
---
> /area …

feat(rules): New `Suspicious Vault client DLL load` rule

---

rules/persistence_potential_port_monitor_or_print_processor_persistence_via_registry_modification.yml

Identifies port monitor or print process registry modifications that would allow adversaries to run malicious DLLs during system boot.
---
> /kind design
---
> /area yara
> …

feat(rules): New `Potential port monitor or print processor persistence via registry modification` rule

---

pkg/ps/snapshotter_windows.go
pkg/ps/snapshotter_windows_test.go

If the module is loaded for the process executable, and we don't have the full executable path, override it with the one from the image path if it corresponds to the process executable
---
> /kind design
---
> …

fix(ps): Spurious process executable override

---

rules/credential_access_credential_discovery_via_vaultcmd.yml

Make the rule more resistant to evasion by checking the original process executable name and also performing case-insensitive match on the command line.
---
> /kind design
--- …

refactor(rules): Improve `Credential discovery via VaultCmd tool` rule

---

rules/initial_access_microsoft_office_file_execution_via_script_interpreter.yml
rules/macros/macros.yml

Identifies the execution via Windows script interpreter of the executable file written by the Microsoft Office process.
---
> /kind design
---
> /area yara
> /area event
> …

feat(rules): New `Microsoft office file execution via script interpreter` rule

---

rules/defense_evasion_suspicious_windows_defender_exclusions_registry_modification.yml

Identifies the modification of the Windows Defender process, path, or IP address registry key exclusions by suspicious processes. Adversaries may alter the Windows Defender exclusions to bypass defenses.
---
> /kind design
---
> …

feat(rules): New `Suspicious Windows Defender exclusions registry modification` rule

---

rules/defense_evasion_windows_defender_protection_tampering_via_registry.yml

Detects suspicious processes modifying Windows Defender configuration settings via registry to disable protection features.
---
> /kind design
---
> /area yara
> /area event …

feat(rules): New `Windows Defender protection tampering via registry` rule

---

rules/defense_evasion_dll_sideloading_via_microsoft_office_dropped_file.yml

Identifies Microsoft Office process creating a DLL or other variant of an executable object which is later loaded by a trusted binary. Adversaries may exploit this behavior by delivering malicious modules via Microsoft Office documents.
---
> /kind design
---
> Uncomment one or more `/area <>` …

feat(rules): New `DLL Side-Loading via Microsoft Office dropped file` rule

---

rules/initial_access_macro_execution_via_script_interpreter.yml

The condition on whether the Microsoft Office process is spawned by the script interpreter should be evaluated on the `ps.name` field.
---
> /kind design
---
> /area yara
> …

fix(rules): Use `ps.name` field in `Macro execution via script interpreter` rule

---

rules/credentail_access_file_access_to_sam_database.yml
rules/credential_access_potential_sam_hive_dumping.yml
rules/credential_access_suspicious_vault_client_dll_load.yml
rules/defense_evasion_dotnet_assembly_loaded_by_unmanaged_process.yml
rules/defense_evasion_hidden_registry_key_creation.yml
rules/defense_evasion_potential_process_injection_via_tainted_memory_section.yml
rules/defense_evasion_process_execution_from_self_deleting_binary.yml
rules/defense_evasion_suspicious_access_to_the_hosts_file.yml
rules/defense_evasion_suspicious_dll_loaded_via_memory_section_mapping.yml
rules/defense_evasion_suspicious_object_symbolic_link_creation.yml
rules/defense_evasion_unsigned_dll_injection_via_remote_thread.yml
rules/initial_access_suspicious_dll_loaded_by_microsoft_office_process.yml

Reduce false positives in various rules by adding exceptions for process executables or file paths.
---
> /kind design
---
> /area yara
> /area event
> /area …

fix(rules): Reduce false positives

---

pkg/event/category.go
pkg/event/category_test.go
pkg/filter/ql/literal.go
pkg/rules/engine.go
pkg/rules/engine_test.go

Move away from FNV hash-based filter indexing to two separate buckets - one for event type filters and one for category filters.
---
> /kind design
---
> /area yara
> /area …

perf(rule-engine): More efficient filter indexing

---

pkg/util/wildcard/wildcard.go

Avoid unnecessary conversion to rune slice to alleviate the pressure on the heap allocator from copy operations.
---
> /kind design
---
> /area yara
> /area event
> /area …

perf: Speed up the `wildcard` function

---

CONTRIBUTING.md
make.bat

Initialize the `VERSION` variable to `0.0.0` (dev) if it is not provided.
---
> /kind design
---
> /area yara
> /area event
> /area …

chore(build): Initialize version variable to dev  if unset

---

pkg/fs/dev.go
pkg/fs/dev_test.go

Some paths may contain the `SystemRoot` prefix (e.g. ` \SystemRoot\system32\drivers\wd\WdNisDrv.sys`) instead of DOS device name. For the sake of consistency, we resolve the SystemRoot environment variable and replace the SystemRoot prefix with the value of the environment variable.
---
> /kind design
> /kind other (change that doesn't pertain to any of the above …

fix(fs): Expand SystemRoot in file paths

---

rules/defense_evasion_windows_defender_driver_unloading.yml
rules/macros/macros.yml

Detects the unloading of Windows Defender kernel-mode drivers, such as WdFilter.sys or WdBoot.sys, which may indicate an attempt to impair or disable antivirus protections.
Adversaries may unload these drivers to bypass or disable real-time scanning, file system filtering, or ELAM (Early Launch Anti-Malware) protections. Legitimate driver unloads are rare and should be investigated to rule out malicious tampering or post-exploitation activity.
---
> /kind breaking (fix or feature that would cause existing functionality …

feat(rules): New `Windows Defender driver unloading` rule

---

pkg/config/_fixtures/filters/default.yml
pkg/config/filters.go
pkg/config/filters_test.go
pkg/config/schema_windows.go

The new `authors` field allows specifying one or more authors of the detection rule.
---
> /kind design
---
/area filters
> /area yara
> /area event
> …

feat(config,rules): Add authors field in rule definition

---

internal/bootstrap/bootstrap.go
pkg/config/config_windows.go

This PR introduces a change to avoid compiling the ruleset if Fibratus is instructed to run the filament.
---
> /kind design
---
> /area yara
> /area event
> …

fix(bootstrap): Don't compile rules if filament is supplied
