- docs/_coverpage.md
- docs/_sidebar.md
- docs/filters/fields.md
- docs/filters/filtering.md
- docs/filters/paths.md
- docs/outputs/console.md
Contains docs changes related to parent filter fields and other path segments.
> docs(filter): Parent filters

- docs/filaments/executing.md
Describes how to pass extra arguments to a filament.
> docs(filament): Filament arguments

- docs/_sidebar.md
- docs/filters/rules.md
Everything that's needed to understand rule semantics.
> docs(filter): Rules

- docs/filters/operators.md
- docs/themes/fibratus.css
Documents fuzzy operators. Restructures operators' page layout a bit.
> docs(filter): Fuzzy operators

- .github/workflows/master.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
> chore: Bump Go to 1.17

- pkg/filter/filter_test.go
- pkg/filter/ql/function.go
- pkg/filter/ql/function_test.go
- pkg/filter/ql/functions/base.go
- pkg/filter/ql/functions/base_test.go
- pkg/filter/ql/functions/cidr_test.go
- pkg/filter/ql/functions/dir.go
- pkg/filter/ql/functions/dir_test.go
- pkg/filter/ql/functions/ext.go
- pkg/filter/ql/functions/ext_test.go
- pkg/filter/ql/functions/glob.go
- pkg/filter/ql/functions/glob_test.go
- pkg/filter/ql/functions/indexof_test.go
- pkg/filter/ql/functions/is_abs.go
- pkg/filter/ql/functions/is_abs_test.go
- pkg/filter/ql/functions/length_test.go
- pkg/filter/ql/functions/regex_test.go
- pkg/filter/ql/functions/replace_test.go
- pkg/filter/ql/functions/substr_test.go
- pkg/filter/ql/functions/symlink.go
- pkg/filter/ql/functions/symlink_test.go
- pkg/filter/ql/functions/types.go
- pkg/filter/ql/functions/volume.go
- pkg/filter/ql/functions/volume_test.go
- pkg/filter/ql/literal.go
- pkg/filter/ql/parser.go
This PR includes a collection of filter functions for file path manipulation as specified in the #134 issue to resolve.
> feat(filter): File path filter functions

- docs/_coverpage.md
- docs/filters/fields.md
- docs/filters/functions.md
- docs/filters/introduction.md
- docs/filters/rules.md
- rules/README.md
This includes all new features, as well as updating deprecated functionality. Also, function examples are simplified and hopefully should better communicate their purpose.
> docs: Docs for the version 1.10.0

- pkg/kevent/kparams/fields_windows.go
* A typo issue is fixed
* It might be useful to show tcp start time and end time.
> feat: Add additional TCP fields and typo fix

- pkg/kstream/processors/image_windows.go
If the image is reported without a checksum value, we compute one by producing a hash of full image path + process id loading the image.
> fix: Compute image checksum if empty

- internal/bootstrap/bootstrap.go
In order to prevent multiple instances of Fibratus process being run at a time, we create a global event object. If creating an event object fails, it means, it is already owned by another Fibratus process. If we allowed users to spawn multiple instances, that would negatively impact event processing and tracing session management.
> feat: Ensure only one instance of Fibratus can be run simultaneously

- docs/_coverpage.md
- docs/_sidebar.md
- docs/filters/fields.md
- docs/filters/filtering.md
- docs/filters/prefiltering.md
- docs/kevents/driver.md
- docs/kevents/file.md
- docs/kevents/handle.md
- docs/kevents/image.md
- docs/kevents/mem.md
- docs/kevents/network.md
- docs/kevents/process.md
- docs/kevents/registry.md
- docs/kevents/thread.md
Documentation changes for the version 2.0.0
> docs: Documentation changes for the version 2.0.0

- pkg/aggregator/transformers/transformer.go
- pkg/alertsender/sender.go
- pkg/filter/ql/functions/entropy.go
- pkg/outputs/outputs.go
> fix: Address various typos

- .github/workflows/master.yml
- .github/workflows/pr.yml
- .github/workflows/rules.yml
- cmd/fibratus/app/root.go
- cmd/fibratus/app/rules/validate.go
- go.mod
- go.sum
- pkg/config/config_windows.go
A new command with its respective `validate` command is incorporated to perform the validation of detection rules. The GitHub Actions workflow is provided to leverage the above command and automate the rules validation process.
> feat(cli): Rules validation command

- .github/workflows/rules.yml
- make.bat
Remove remnants of old target and rename install-msi to install.
> refactor(build): Tidy up make.bat

- rules/macros/macros.yml
- rules/privilege_escalation_exploitation_for_privilege_escalation.yml
Two new rules to detect the dropping and loading of vulnerable/malicious drivers.
> feat(rules): Exploitation for Privilege Escalation via LOL drivers

- rules/persistence_office_application_startup.yml
Eliminate potential false positives from `Program Files` directories and change the rule output string.
> chore(rules): Improve `Suspicious Office template created` rule

- pkg/filter/rules.go
- pkg/filter/rules_test.go
Temporal distance error is error-prone and not very valuable since the vast majority of events are emitted from the NT Kernel Logger provider. Additionally, the logic for determining unordered partials is self-sufficient to match out-of-order
events.
> fix(rule-engine): Ditch temporal distance calculation

- pkg/filter/filter_test.go
Fix test expectation in thread callstack accessor.
> fix(test): Expectation in thread callstack accessor

- rules/defense_evasion_process_injection.yml
Identifies unsigned DLL injection via remote thread creation.
> feat(rules): New `Unsigned DLL injection via remote thread` rule

- .github/workflows/master.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- build/msi/fibratus.wxs
- make.bat
This changeset contains the necessary bits to migrate the MSI build system to Wix 5.0
> build(msi): Migrate to Wix 5.0.0

- pkg/kevent/formatter.go
- pkg/kevent/formatter_windows.go
This PR brings the ability to render the event's full call stack via console output.
> chore(output): Add callstack console output template field

- cmd/fibratus/app/root.go
- cmd/fibratus/app/service/install_service_windows.go
- cmd/fibratus/fibratus.rc
Change CLI command short and long descriptions and version resources of the Fibratus binary.
> refactor: Rebrand product message

- .github/workflows/release.yml
- README.md
- docs/overview/what-is-fibratus.md
Align upload/download actions to use the same version, and fix typos.
> ci(workflows): Fix release job

- docs/index.html
- docs/kevents/anatomy.md
- docs/outputs/console.md
- docs/setup/quick-start.md
Improvements to docs and leftover fixes.
> docs:  Various docs improvements

- cmd/systray/main_windows.go
As observed in certain circumstances, the systray server process may fail to listen on the namedpipe with "Access denied" error. Setting the security descriptor on the named pipe should hopefully correct this situation.
> fix(systray-server): Set namedpipe security descriptor

- docs/_coverpage.md
Increment release version as there are no more substantial changes in the 2.2.1 release.
> docs: Increment release version

- .github/PULL_REQUEST_TEMPLATE.md
The pull request template for better communicating the proposed changeset.
> chore: Introduce pull request template

- .github/workflows/pr.yml
Introduces an action to validate PR titles that conform to the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec standards.
> ci(workflows): Enforce conventional semantic PR titles

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/pr.yml
This PR improves the pull request template to better convey the changeset it is introducing.
> chore(ci): Restructure pull request template

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support.md
Include templates for issues, feature requests, and support asks.
> chore: Introduce issues templates

- .github/PULL_REQUEST_TEMPLATE.md
It polishes the pull request template by adding an additional `Filters` project area, fixes a typo, and thoroughly explains how to mark the available options to avoid confusion.
> chore: Polish pull request template

- CONTRIBUTING.md
- README.md
Provide all the necessary information for bootstrapping the dev environment and building Fibratus. Clearly communicate the pull request requirements and preferred git usage.
> chore: Improve contributing guidelines

- pkg/alertsender/alert.go
- pkg/filter/action/emit.go
- pkg/filter/rules_test.go
- pkg/yara/scanner.go
The alert identifier maps the alert to their respective runtime behavior or YARA rules.
> chore(alertsenders): Add alert identifier

- configs/fibratus.yml
- pkg/alertsender/alert.go
- pkg/alertsender/alert_test.go
- pkg/alertsender/eventlog/config.go
- pkg/alertsender/eventlog/eventlog.go
- pkg/alertsender/eventlog/eventlog_test.go
- pkg/config/schema_windows.go
- pkg/filter/action/emit.go
- pkg/filter/rules_test.go
- pkg/ps/types/types_windows.go
When in verbose mode, the eventlog alert sender, will include the full event context that comprises the event data, all event parameters, and the process information.
This introduces a new config option to control if the full event information is displayed in the security alert. The documentation needs to reflect the new feature of the eventlog sender.
> feat(alertsenders/eventlog): Introduce verbose mode

- .gitattributes
- .golangci.yml
- make.bat
- pkg/filter/accessor_windows_test.go
- pkg/kevent/ktypes/eventset_test.go
gofmt linter check if the code was gofmt-ed. To avoid false positives we change the git line endings to lf.
No
> chore(linter): Introduce gofmt linter

- make.bat
Linter jobs occasionally fail when the timeout
is reached. Increment the timeout to hopefully
fix the failures.
> fix(ci,linter): Increment linter timeout

- rules/credential_access_lsass_memory_dump_via_wer.yml
- rules/credential_access_lsass_memory_dumping.yml
- rules/defense_evasion_dll_sideloading_via_copied_binary.yml
- rules/defense_evasion_potential_process_doppelganging_injection.yml
- rules/defense_evasion_potential_process_injection_via_tainted_memory_section.yml
- rules/initial_access_execution_via_microsoft_office_process.yml
- rules/initial_access_macro_execution_via_script_interpreter.yml
- rules/initial_access_suspicious_dll_loaded_by_microsoft_office_process.yml
- rules/persistence_network_connection_via_startup_folder_executable_or_script.yml
Reformat rule conditions to improve readability.
> chore(rules): Reformat rule conditions

- .github/PULL_REQUEST_TEMPLATE.md
Make the pull request template require less legwork to fill out.
> chore: Reorganize pull request template

- README.md
- rules/README.md
Include the rules section in the README and explains how to create a new rule from the template.
---
> /kind design
---
> /area yara
> /area event
> /area …
> chore: Include rules section in the README

- LICENSE.MD
Updates the copyright date of the license file.
---
/kind cleanup
> /kind design
---
> /area yara
> /area event
> /area rules
> /area …
> chore: Update license copyright date

- README.md
Cosmetic README change to get rid of the rules table.
---
> /kind design
/kind other (change that doesn't pertain to any of the above categories)
---
> /area yara
> /area event
> /area rules
> …
> chore: Cosmetic README change

- pkg/ps/peb.go
If the env variable contains multiple = symbols,
we make sure the split will always produce two
substrings. When reading the env block, use
the buffer size as the size of the read memory
area.
---
> /kind design
---
> /area …
> fix(process): Solidify env var parsing

- rules/credential_access_credential_access_from_backups_via_rundll32.yml
Leftovers from previous migration of the deprecated `pe.ps.child.file.name` filter field.
> chore(rules): Replace deprecated filter field

- rules/credential_access_remote_thread_creation_into_lsass.yml
- rules/persistence_script_interpreter_or_untrusted_process_persistence.yml
- rules/persistence_suspicious_persistence_via_registry_modification.yml
Using the not operator on bool fields leads to misbehavior. Instead, use the equal operator and false keyword.
> fix(rules): Correct usage of not operator on bool fields

- go.mod
- go.sum
Bump `www.velocidex.com/golang/go-ntfs` to latest version.
> chore(deps): Bump `www.velocidex.com/golang/go-ntfs` to latest version

- internal/etw/processors/processor.go
If the file can be opened, we proceed with parsing the PE metadata by directly accessing the file. On the contrary, the raw device access is performed to read the file data blob and pass it to the PE parser.
---
> /kind design
--- …
> fix(processors): Fix parsing of image file characteristics

- .github/workflows/release.yml
- README.md
The code signing is performed by the SignPath
GitHub Action. All releases are automatically
signed - both the MSI and all the binaries/DLLs.
---
> /kind design
---
> /area …
> feat(ci): Introduce digital signing

- docs/alerts/senders/mail.md
Update mail.md file adding a note about configuring Gmail as mail provider in alert senders.
---
> /kind design
/kind documentation
---
> /area yara
> /area event
> /area …
> docs: Add NOTE in mail.md about Gmail SMTP provider

- docs/alerts/senders/mail.md
Fix style in mail.md NOTE about Gmail SMTP provider.
---
> /kind design
/kind documentation
---
> /area yara
> /area event
> /area rules
> …
> style: Fix NOTE in mail.md about Gmail SMTP provider

- internal/etw/processors/ps_windows.go
If we fail to obtain the process start time
use the one from the event timestamp.
---
> /kind design
---
> /area yara
/area event
> …
> fix(ps): Use start time from event timestamp

- pkg/symbolize/symbolizer.go
When the single address is symbolized and its backing module is not found in the current process modules, query the parent
process modules.
---
> /kind design
---
> /area yara …
> fix(symbolizer): Lookup parent modules

- internal/etw/source.go
If the event source is already closed, an attempt to close the channel twice will occur, leading to a panic. To mitigate this, we check if the source is already closed, in which case we return early.
---
> /kind design
---
> /area …
> fix(event-source): Ensure event source is closed once

- pkg/filter/filter.go
- pkg/filter/filter_test.go
Make it possible to use argument-based filter fields in the rule output.
---
> /kind design
---
/area filters
> /area yara
> /area event
> …
> fix(filter): Interpolation for arg-based fields

- .github/workflows/pr.yml
Changed the `changed-files` action input only to consider modified files.
---
> /kind design
---
> /area yara
> /area event
> /area …
> fix(ci): Only consider modified rules

- pkg/rules/sequence.go
If the process termination event arrives, and the sequence contains `CreateThread` events where the event pid and the pid in the parameters differ, the sequence can be expired when the remote process terminates.
---
> /kind design
---
> /area …
> fix(rule-engine): Add expire sequence condition for CreateThread event

- rules/persistence_suspicious_microsoft_office_addin_loaded.yml
Identifies attempts to load unsigned executables from Microsoft Office add-ins directories, which adversaries may exploit to maintain persistence.
---
> /kind design
---
> …
> feat(rules): New `Suspicious Microsoft Office add-in loaded` rule

- rules/initial_access_microsoft_office_file_execution_via_wmi.yml
Identifies the execution via Windows Management Instrumentation (WMI) of the binary file written by the Microsoft Office process. Attackers can exploit WMI to silently execute malicious code.
---
> /kind design
---
> /area …
> feat(rules): New `Microsoft Office file execution via WMI` rule
